### ISSUE TITLE
Can't [Retrieving User Details from an Access Token]

### ISSUE THREAD

**Issue by hsakamoto123** [FIWARE/tutorials.Securing-Access#9]
1️⃣ Request
curl -iX POST \
  'http://localhost:3005/oauth2/token' \
  -H 'Accept: application/json' \
  -H 'Authorization: Basic dHV0b3JpYWwtZGNrci1zaXRlLTAwMDAteHByZXNzd2ViYXBwOnR1dG9yaWFsLWRja3Itc2l0ZS0wMDAwLWNsaWVudHNlY3JldA==' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data "username=alice-the-admin@test.com&password=test&grant_type=password"

1️⃣ Response
HTTP/1.1 200 OK
Content-Security-Policy-Report-Only: default-src *;font-src *;img-src *;script-src *;style-src *;form-action *;base-uri 'self';block-all-mixed-content;frame-ancestors 'self';object-src 'none';script-src-attr 'none';upgrade-insecure-requests
X-DNS-Prefetch-Control: off
Expect-CT: max-age=0
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
X-XSS-Protection: 0
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Type: application/json; charset=utf-8
Content-Length: 177
ETag: W/"b1-dEvh3fIvHPpfsjT7Lv1vPSlvyMM"
Set-Cookie: session=eyJyZWRpciI6Ii8ifQ==; path=/; expires=Fri, 09 Dec 2022 09:54:05 GMT; httponly
Set-Cookie: session.sig=Ri-h5xOEppsonbO3FRtvV1LbiI0; path=/; expires=Fri, 09 Dec 2022 09:54:05 GMT; httponly
Date: Fri, 09 Dec 2022 08:54:05 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"access_token":"bdb557638136aa3cefeede95e8f54b2387c4caac","token_type":"bearer","expires_in":3599,"refresh_token":"b06d558efaba5008f0c6c478105ac37c31be57b8","scope":["bearer"]}

2️⃣ Request
curl -X GET \
  'http://localhost:3005/user?access_token=bdb557638136aa3cefeede95e8f54b2387c4caac'

2️⃣ Response
"Internal error"

2️⃣ container log
.........
{"log":"}\n","stream":"stderr","time":"2022-12-09T08:54:05.75700422Z"}
{"log":"2022-12-09T08:56:32.804Z idm:oauth_controller  --\u003e authenticate_token\n","stream":"stderr","time":"2022-12-09T08:56:32.805070778Z"}
{"log":"2022-12-09T08:56:32.805Z idm:oauth_controller  --\u003e authenticate_bearer\n","stream":"stderr","time":"2022-12-09T08:56:32.805140263Z"}
{"log":"2022-12-09T08:56:32.805Z idm:oauth2-model_oauth_server -------getAccessToken-------\n","stream":"stderr","time":"2022-12-09T08:56:32.805633026Z"}
{"log":"2022-12-09T08:56:32.815Z idm:oauth2-model_oauth_server -------create_oauth_response-------\n","stream":"stderr","time":"2022-12-09T08:56:32.815953537Z"}
{"log":"2022-12-09T08:56:32.817Z idm:oauth2-model_oauth_server -------search_user_info-------\n","stream":"stderr","time":"2022-12-09T08:56:32.817503946Z"}
{"log":"2022-12-09T08:56:32.817Z idm:oauth2-model_oauth_server -------trusted_applications-------\n","stream":"stderr","time":"2022-12-09T08:56:32.817596504Z"}
{"log":"2022-12-09T08:56:32.817Z idm:oauth2-model_oauth_server -------user_roles-------\n","stream":"stderr","time":"2022-12-09T08:56:32.817781913Z"}
{"log":"2022-12-09T08:56:32.819Z idm:oauth2-model_oauth_server Error:  Error: WHERE parameter \"oauth_client_id\" has invalid \"undefined\" value\n","stream":"stderr","time":"2022-12-09T08:56:32.819656578Z"}
{"log":"    at MySQLQueryGenerator.whereItemQuery (/opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1658:13)\n","stream":"stderr","time":"2022-12-09T08:56:32.819666142Z"}
{"log":"    at /opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1649:25\n","stream":"stderr","time":"2022-12-09T08:56:32.81966817Z"}
{"log":"    at Array.forEach (\u003canonymous\u003e)\n","stream":"stderr","time":"2022-12-09T08:56:32.819669997Z"}
{"log":"    at MySQLQueryGenerator.whereItemsQuery (/opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1647:35)\n","stream":"stderr","time":"2022-12-09T08:56:32.819671889Z"}
{"log":"    at MySQLQueryGenerator.getWhereConditions (/opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1990:19)\n","stream":"stderr","time":"2022-12-09T08:56:32.819673602Z"}
{"log":"    at MySQLQueryGenerator.selectQuery (/opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-generator.js:932:28)\n","stream":"stderr","time":"2022-12-09T08:56:32.819675302Z"}
{"log":"    at MySQLQueryInterface.select (/opt/fiware-idm/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)\n","stream":"stderr","time":"2022-12-09T08:56:32.81967699Z"}
{"log":"    at Function.findAll (/opt/fiware-idm/node_modules/sequelize/lib/model.js:1134:47)\n","stream":"stderr","time":"2022-12-09T08:56:32.819678649Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n","stream":"stderr","time":"2022-12-09T08:56:32.819680323Z"}
{"log":"    at async Promise.all (index 0)\n","stream":"stderr","time":"2022-12-09T08:56:32.819681928Z"}
{"log":"2022-12-09T08:56:32.819Z idm:oauth_controller Error  { message: 'Internal error', code: 500, title: 'Internal error' }\n","stream":"stderr","time":"2022-12-09T08:56:32.820609706Z"}

Am I doing something wrong?
I'm looking into the 'js' file, but I don't understand the cause.

**Comment by hsakamoto123** [comment]
I changed the .env file and it worked.
Thank you.

**Comment by jason-fox** [comment]
This appears to be a reversion in **Keyrock**

'http://localhost:3005/user?access_token=bdb557638136aa3cefeede95e8f54b2387c4caac' **FAILS*

'http://localhost:3005/user?access_token=bdb557638136aa3cefeede95e8f54b2387c4caac&app_id=tutorial-dckr-site-0000-xpresswebapp' **SUCCEEDS**

trusted_apps is not working correctly.

I have added a PR here: https://github.com/ging/fiware-idm/pull/306/files#diff-f691da4cc147d46d9035711e2a22a0f552cd822defaf8453f89e708448a3d91f

**Comment by jason-fox** [comment]
As a workaround I have updated the API call in the documentation. The [Bug Fix](https://github.com/ging/fiware-idm/pull/306) has been **merged**  so will be available as part of the next Keyrock release.
